###############################################################################
# dns servers
###############################################################################

# list of external dns servers
dns:
  servers:
    - 8.8.8.8
    - 8.8.4.4
