###############################################################################
# ntp servers
###############################################################################

# list of external ntp servers
ntp:
  servers:
    - time1.google.com
    - time2.google.com
