chef_roles:
  - name: node
    description: common role for all bcpc nodes
    json_class: Chef::Role
    chef_type: role
    run_list:
      - recipe[bcpc::apt]
      - recipe[bcpc::ssl]
      - recipe[bcpc::cloud-archive]
      - recipe[bcpc::chrony]
      - recipe[bcpc::postfix]
      - recipe[bcpc::common-packages]
      - recipe[bcpc::kexec]
      - recipe[bcpc::apport]
      - recipe[bcpc::etckeeper]
      - recipe[bcpc::cpupower]
      - recipe[bcpc::getty]
      - recipe[bcpc::hwrng]
      - recipe[bcpc::system]

  - name: bootstrap
    description: bootstrap node
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::ssh]
      - recipe[bcpc::file-server]
      - recipe[bcpc::ufw]
      - recipe[bcpc::rally]

  - name: headnode
    description: cloud infrastructure services
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::haproxy]
      - recipe[bcpc::ssh]
      - recipe[bcpc::etcd-member]
      - recipe[bcpc::rabbitmq]
      - recipe[bcpc::memcached]
      - recipe[bcpc::unbound]
      - recipe[bcpc::consul]
      - recipe[bcpc::ceph-mon]
      - recipe[bcpc::ceph-mgr]
      - recipe[bcpc::mysql]
      - recipe[bcpc::powerdns]
      - recipe[bcpc::apache2]
      - recipe[bcpc::keystone]
      - recipe[bcpc::glance]
      - recipe[bcpc::neutron-head]
      - recipe[bcpc::nova-head]
      - recipe[bcpc::cinder]
      - recipe[bcpc::horizon]
      - recipe[bcpc::os-quota]
      - recipe[bcpc::flavors]

  - name: storagenode
    description: storage node
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::ceph-osd]

  - name: worknode
    description: cloud compute services
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::etcd-proxy]
      - recipe[bcpc::calico-work]
      - recipe[bcpc::nova-compute]
