network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 10.0.2.15/24
      nameservers:
        addresses:
          - 10.0.2.3
    eth1: # s1r2t2
      addresses:
        - 172.16.1.7/31
    eth2: # s2r2t2
      addresses:
        - 172.16.2.7/31
    eth3: #r2t2
      addresses:
        - 10.129.2.17/28
