network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1: # s1r1t1
      addresses:
        - 172.16.1.0/31
    eth2: # s1r1t2
      addresses:
        - 172.16.1.2/31
    eth3: # s1r2t1
      addresses:
        - 172.16.1.4/31
    eth4: # s1r2t2
      addresses:
        - 172.16.1.6/31
    eth5: # s1r3t1
      addresses:
        - 172.16.1.8/31
    eth6: # s1r3t2
      addresses:
        - 172.16.1.10/31
